{{- if .Values.configvalues }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
{{ range $k, $v :=  .Values.configvalues }}
  {{$k}}: "{{$v}}"
{{ end }}
{{- end }}
