{{- if eq .Values.rollout_vt_a.enabled "true" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "common.name" . }}-a
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.disruption.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "common.fullname" . }}-a
{{- end }}

---
{{- if eq .Values.rollout_vt_b.enabled "true" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "common.name" . }}-b
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.disruption.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "common.fullname" . }}-b
{{- end }}