{{- if .Values.externalsecrets.enabled }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" . }}
  annotations:
{{- toYaml .Values.externalsecrets.annotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ include "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  backendType: secretsManager
  dataFrom:
    - {{ .Values.externalsecrets.name }}
{{- end }}