{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.secrets.name }}{{ .Values.secrets.name }}{{ else }}{{ include "common.fullname" . }}{{ end }}
  annotations:
{{- toYaml .Values.secrets.annotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ include "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
{{- toYaml .Values.secrets.values | nindent 2 }}
{{- end }}