{{- if .Values.extraConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.extraConfigMap.name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
{{ toYaml .Values.extraConfigMap.data | nindent 2 }}
{{- end }}
