{{- if .Values.autoscaling.enabled }}
{{- $fullName := include "common.fullname" . -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ $fullName }}
  {{- if .Values.autoscaling.hpaannotation.enabled }}
  annotations:
  {{- with .Values.autoscaling.hpaannotation.annotation }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "common.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{- with .Values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.autoscaling.metrics }}
  metrics:
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
