{{- if ((.Values.istio).enabled) }}
{{- if ((.Values.istio.virtualService).enabled) }}
{{- range $key, $value := .Values.istio.virtualService.virtualServices }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "common.labels" $ | indent 4 }}
spec:
  gateways:
  {{- range .gateways }}
  - {{.}}
  {{- end }}
  hosts:
  {{- range .hosts }}
  - {{.}}
  {{- end }}
  http:
  {{- range $app := $value.apps }}
  {{- if $app.path }}
  - match:
      - uri:
          prefix: "{{ $app.path }}"
    name: {{ $app.name }}    
  {{- else }}
  - name: {{ $app.name }}
  {{- end }}
    route:
    {{- range $route := $app.routes }}
    - destination:
          host: {{ $route.name }}
          #subset: {{ $route.name }}
          port:
            number: {{ $route.port  }}
      weight: {{ $route.weight  }}
    {{- end }}
    {{- if $app.retries }}
    retries:
    {{- toYaml $app.retries | nindent 6 }}
    {{- end }}
	{{- end }}
---
{{- end }}
{{- end }}
{{- end }}