{{- if and .Values.serviceAccount.create .Values.rbac.rules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "common.name" . }}-rolebinding
  labels:
    app.kubernetes.io/name: {{ include "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "common.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "common.name" . }}
{{- end }}

