{{- if and .Values.serviceAccount.create .Values.rbac.rules}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "common.name" . }}-role
  labels:
    app.kubernetes.io/name: {{ include "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules: 
{{ toYaml .Values.rbac.rules }}
{{- end }}
