apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.stable.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.stable.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ include "common.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.isHeadless }}
  clusterIP: None
  {{- end }}
{{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    {{- $setNodePorts := (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) }}
    {{- if .Values.service.enableHttp }}
    - name: http
      port: {{ .Values.service.ports.http }}
      protocol: TCP
      targetPort: {{ .Values.service.http_port | default .Values.image.port }}
      {{- if (and $setNodePorts (not (empty .Values.service.nodePorts.http))) }}
      nodePort: {{ .Values.controller.service.nodePorts.http }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.enableHttps }}
    - name: https
      port: {{ .Values.service.ports.https }}
      protocol: TCP
      targetPort: {{ .Values.service.https_port | default .Values.image.port }}
      {{- if (and $setNodePorts (not (empty .Values.service.nodePorts.https))) }}
      nodePort: {{ .Values.service.nodePorts.https }}
      {{- end }}
    {{- end }}
{{- if .Values.extraPorts }}
{{ toYaml .Values.extraPorts | trim | indent 4 }}
{{- end }}
  selector:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}


